### ISSUE TITLE
Docker command show error on running

### ISSUE THREAD

**Issue by cor277** [gpt-engineer-org/gpt-engineer#933]
when try to run the gpt-engineer from docker I recieve this error :

docker run -it --rm -e OPENAI_API_KEY=sk-iv9R5S5u0XqSmTdR1JnOT3BlbkFJSxxxxxxxxx -v .\:/project gpt-engineer
**/app/entrypoint.sh: line 3: $'\r': command not found
 unning gpt-engineer in /project**

What application do you want gpt-engineer to generate?
^C <--------- i tstopped the run for error above.

**Comment by arghhjayy** [comment]
Can't replicate this, maybe this is fixed?
Can you try again and check?

**Comment by k1lgor** [comment]
@cor277 @oldmanjk  It seems that the `entrypoint.sh` file may have a `CRLF` end of the file, which could be causing the issue. To resolve this, try changing it to `LF`. In `CRLF`, every new line is marked by `\n\r`, but Unix does not recognize the `\r` character. Changing to `LF` should fix the problem.

**Comment by viborc** [comment]
@oldmanjk are you still experiencing this error? It's been a while since this issue was last active and if it's not relevant anymore, I'd like to close it.

Please, let us know.

**Comment by captivus** [comment]
@zigabrencic will review in conjunction with #1136 and, pending resolution, will close.

**Comment by k1lgor** [comment]
Here is the replication of the error mentioned:
Open the `entrypoint.sh` file in VSCode and click at the bottom on the editor 
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/65338982/3fbcc094-7627-48ae-be9b-b29b1b320f48)
and choose `CRLF` at the top. If you build the container now, will be successful, but executing the `entrypoints.sh` file inside the container wont be
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/65338982/60f007c6-04be-4cc0-a571-0e98177a812b)
because the shell does not recognize the `CRLF` ending of the line. This is happening while you create files under Windows env.

**Comment by viborc** [comment]
Hey, @k1lgor! We just made a [new release - v0.3.1](https://github.com/gpt-engineer-org/gpt-engineer/releases/tag/v0.3.1), and the Docker hotfix you proposed is included. 

Can you confirm that it's also solving this issue #933 so we can close it?

**Comment by k1lgor** [comment]
Hey @viborc, I believe this can be closed. Just a note for everyone who wants to use the `.sh` file inside docker: the file's end of line must be `LF`.
