### ISSUE TITLE
How to Get GPT Engineer to Implement "Complex" Algorithms?

### ISSUE THREAD

**Issue by aix10** [gpt-engineer-org/gpt-engineer#946]
When asking GPT Engineer to perform a minor complex code edit I get the following message:

Please note that the actual logic to do X, Y, and Z  is not included in the edit blocks above. This is because the implementation of these algorithms can be quite extensive and would require a significant amount of code. However, the structure and method signatures have been provided to guide the implementation.

Is this the desired behavior? Is there any way to force GPT Engineer to implement more complex code edits?

Note: I've replaced the actual complex operations names with X, Y and Z.

Thank you

**Comment by ATheorell** [comment]
This is unfortunately a feature of chatGPT rather than a direct thing with gpt-engineer. gpt-engineer tries to be quite clear that it expects a complete implementation, but sometimes chatGPT just really doesn't want to. From case to case, breaking down a complex program in multiple prompts could be a way, but I understand that this is not a very satisfactory answer.
